name: 'Module Graph'

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  module-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build nuxt.js app
        run: yarn build

      - name: Get changed files
        id: changed-files
        if: github.event.number
        uses: tj-actions/changed-files@v12.2

      - name: List all modified files
        if: github.event.number
        run: |
          echo ${{ steps.changed-files.outputs.all_modified_files }}

      - name: Generate Module Graph
        if: github.event.number
        run: yarn generate:module-graph ${{ steps.changed-files.outputs.all_modified_files }}
      - name: Get comment body
        id: get-comment-body
        if: success() && github.event.number
        run: |
          if [ ! -e ".nuxt/module_graph/output.txt" ]; then
            body="No affected dependencies."
          else
            body=$(cat .nuxt/module_graph/output.txt)
            body="${body//'%'/'%25'}"
            body="${body//$'\n'/'%0A'}"
            body="${body//$'\r'/'%0D'}"
          fi
          echo ::set-output name=body::$body

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __MODULE_GRAPH -->'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
